export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"614ae9f371cf90001f3204e0",
				"614ae9f371cf90001f3204e2",
				"614b6492845cb0001ebe3d08",
				"614b64948bdb79001eb18e8a"
			]
		},
		"614ae9f371cf90001f3204e0": {
			"id": "614ae9f371cf90001f3204e0",
			"name": "404",
			"pageUrl": "404"
		},
		"614ae9f371cf90001f3204e2": {
			"id": "614ae9f371cf90001f3204e2",
			"name": "index",
			"pageUrl": "index"
		},
		"614b6492845cb0001ebe3d08": {
			"id": "614b6492845cb0001ebe3d08",
			"pageUrl": "4",
			"name": "4"
		},
		"614b64948bdb79001eb18e8a": {
			"id": "614b64948bdb79001eb18e8a",
			"pageUrl": "5",
			"name": "5"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {},
		"seo": {
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated"
		}
	}
}