export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"614ae9f371cf90001f3204e0",
				"614ae9f371cf90001f3204e2",
				"614b64ef845cb0001ebe3d0e",
				"614b64f18bdb79001eb18e8e"
			]
		},
		"614ae9f371cf90001f3204e0": {
			"id": "614ae9f371cf90001f3204e0",
			"name": "404",
			"pageUrl": "404"
		},
		"614ae9f371cf90001f3204e2": {
			"id": "614ae9f371cf90001f3204e2",
			"name": "index",
			"pageUrl": "index"
		},
		"614b64ef845cb0001ebe3d0e": {
			"id": "614b64ef845cb0001ebe3d0e",
			"pageUrl": "1",
			"name": "1"
		},
		"614b64f18bdb79001eb18e8e": {
			"id": "614b64f18bdb79001eb18e8e",
			"pageUrl": "2",
			"name": "2"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {},
		"seo": {
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated"
		}
	}
}