export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"614ae9f371cf90001f3204e0",
				"614ae9f371cf90001f3204e2",
				"614b618e5aad94001eb5a502",
				"614b6191845cb0001ebe3d06"
			]
		},
		"614ae9f371cf90001f3204e0": {
			"id": "614ae9f371cf90001f3204e0",
			"name": "404",
			"pageUrl": "404"
		},
		"614ae9f371cf90001f3204e2": {
			"id": "614ae9f371cf90001f3204e2",
			"name": "index",
			"pageUrl": "index"
		},
		"614b618e5aad94001eb5a502": {
			"id": "614b618e5aad94001eb5a502",
			"pageUrl": "1",
			"name": "1"
		},
		"614b6191845cb0001ebe3d06": {
			"id": "614b6191845cb0001ebe3d06",
			"pageUrl": "2",
			"name": "2"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {},
		"seo": {
			"robotsFileType": "autogenerated",
			"sitemapFileType": "autogenerated"
		}
	}
}